<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Fastfood</title>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="HTML, CSS, XML, JavaScript">
    <meta name="author" content="Sandra Cruz">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300Roboto:300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../css/normalize.css">
    <link rel="stylesheet" type="text/css" href="../css/reset.css">
    <link rel="stylesheet" type="text/css" href="../css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="../css/style.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <div class="container">
        <h1 class="logo">O'Fast</h1>       
    </div>
    <!-- Chargement du template PHTML spécifié par le programme PHP -->
    <?php include $template.'.phtml' ?>
    <script src="../js/jquery.js"></script> 
    <script src="../js/materialize.min.js"></script>
    <script src="../js/app.js"></script>
</body>
</html>