<!-- Page fiche produits -->
    <div class="container admin">
        <div class="row">
            <div class="col s12 m6 l6">
                <h2>Voir un produit</h2>
                <form>
                    <div class="form_product">
                        <label>Nom:</label><?php echo ' '. $item ['name']; ?>
                    </div>
                    <div class="form_product">
                        <label>Détails:</label><?php echo ' '. $item ['description']; ?>
                    </div>
                    <div class="form_product">
                        <label>Prix:</label><?php echo ' '. number_format((float) $item['price'],2,'.','') .' €'; ?>
                    </div>
                    <div class="form_product">
                        <label>Catégorie:</label><?php echo ' '. $item ['category']; ?>
                    </div>
                    <div class="form_product">
                        <label>Photo:</label><?php echo ' '. $item ['image']; ?>
                    </div>
                </form>
                <br>
                <div>
                    <a href="index.php"class="waves-effect waves-light btn">Retour</a>
                </div>
                <br>
            </div>
            <div class ="col s12 m6 l6">
                <img src="<?php echo '../image/'. $item ['image']; ?>" alt="menuClassic">
                <div><?php echo number_format((float) $item['price'],2,'.',''). ' €' ; ?></div>
                <div class="caption">
                    <h2><?php echo $item ['name']; ?></h2>
                    <p><?php echo $item ['description']; ?></p>
                    <br>
                    <!-- Pas d'usage de ce bouton dans le projet -->
                    <a href="#" class="waves-effect waves-light btn">Commander</a>
                </div>
            </div>
        </div>  
  